config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  resources :car_forms do
    get 'user_car_forms', on: :collection
    post 'comments', to: 'car_forms#comment'
  end
  
  resources :admin do
    post 'attach_file', on: :member
    delete 'delete_attachment', on: :member
  end

  resources :quotations do
    put 'approval_and_rejection'
  end
  resources :quotation_items
end

app/controllers/car_form_controller.rb
class CarFormController < ApplicationController
  def new
    @car_form = CarForm.new
  end

  def create
    @car_form = CarForm.new(car_form_params)

    if @car_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def car_form_params
    params.require(:car_form).permit(
      :city,
      :address,
      :phone_number,
      :email,
      :vehicle_type,
      :vehicle_identification_number,
      :describe
    )
  end
end

app/controllers/car_forms_controller.rb
class CarFormsController < ApplicationController
  def show
    @car_form = CarForm.find(params[:id])
  end

  def new
    @car_form = CarForm.new
  end

  def create
    @car_form = CarForm.new(car_form_params)


    if @car_form.save
      @car_form.user = current_user
      redirect_to root_path
    else
      render :new
    end
  end

  def user_car_forms
    @car_forms = current_user.car_forms.includes(:quotations)
  end

  def comment
    @car_form = CarForm.find(params[:car_form_id])
    @comment = @car_form.comments.build(content: params[:quotation][:comments][:content])

    if @comment.save
      redirect_to @car_form
    else
      # Handle errors
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def car_form_params
    params.require(:car_form).permit(
      :city,
      :address,
      :phone_number,
      :email,
      :vehicle_type,
      :vehicle_identification_number,
      :describe,
      :user_id
    )
  end
end

app/views/car_forms/new.html.erb
<!-- app/views/car_form/new.html.erb -->

<%= form_with(model: @car_form, url: car_forms_path, method: :post) do |form| %>
  <!-- Display validation errors -->
  <% if @car_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_form.errors.count, "error") %> prohibited this car form from being saved:</h2>
      <ul>
        <% @car_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form fields for car_form attributes -->
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :vehicle_type %>
    <%= form.select :vehicle_type, CarForm.vehicle_types.keys %>
  </div>

  <div>
    <%= form.label :vehicle_identification_number %>
    <%= form.text_field :vehicle_identification_number %>
  </div>

  <div>
    <%= form.label :describe %>
    <%= form.text_area :describe %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <!-- Submit button -->
  <div>
    <%= form.submit 'Submit Car Quotation' %>
  </div>
<% end %>

app/views/car_forms/show.html.erb
<h1>Car Form Details</h1>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @car_form.vehicle_type %> - <%= @car_form.vehicle_identification_number %></h5>
    <p class="card-text">
      <strong>City:</strong> <%= @car_form.city %><br>
      <strong>Address:</strong> <%= @car_form.address %><br>
      <strong>Phone Number:</strong> <%= @car_form.phone_number %><br>
      <strong>Email:</strong> <%= @car_form.email %><br>
      <strong>Vehicle Type:</strong> <%= @car_form.vehicle_type %><br>
      <strong>Vehicle Identification Number:</strong> <%= @car_form.vehicle_identification_number %><br>
      <strong>Describe:</strong> <%= @car_form.describe %><br>
      <strong>User ID:</strong> <%= @car_form.user_id %><br>

      <% if @car_form.quotations.present? %>
        <hr>
        <h5>Quotation Details</h5>
        <strong>Discount:</strong> <%# @car_form.quotation.discount %><br>
        
  <div>
    <% @car_form.quotations.each do |quotation| %>
      <% if quotation.approved? %>
        <p class="text-success">Approved</p>
      <% elsif quotation.approved_by_customer == nil %>
        <div class="btn-group">
          <%= button_to 'Approve',
              quotation_approval_and_rejection_path(quotation, approved: true),
              method: :put, class: 'btn btn-success mt-3 mr-3' %>
          <%= button_to 'Reject',
              quotation_approval_and_rejection_path(quotation),
              method: :put, class: 'btn btn-danger m-3' %>
        </div>
      <% else %>
        <p class="text-danger">Rejected</p>
      <% end %>
    <% end %>
  </div>
      <% else %>
        <p>No quotation associated with this car form.</p>
      <% end %>
    </p>
  </div>
</div>


<div class="mt-3">
  <%= form_with(model: [@car_form, Quotation.new], url: car_form_comments_path(@car_form), method: :post) do |form| %>

    <div class="form-group">
      <%= form.fields_for :comments, Comment.new do |comment| %>
        <%= comment.label :content, 'Comment:' %>
        <%= comment.text_area :content, class: 'form-control', rows: 3 %>
      <% end %>
    </div>

    <%= form.submit 'Submit Comment', class: 'btn btn-primary' %>
  <% end %>

  <% if @car_form.comments.any? %>
    <hr>
    <h5>Comments</h5>
    <ul>
      <% @car_form.comments.each do |comment| %>
        <p><%= comment.content %></p>
      <% end %>
    </ul>
  <% else %>
    <p>No comments for this car form.</p>
  <% end %>
</div>
<%= link_to 'Back', user_car_forms_car_forms_path, class: 'btn btn-secondary mt-3' %>

app/views/car_forms/user_car_forms.html.erb
<!-- app/views/car_forms/user_car_forms.html.erb -->

<h1>User Car Forms</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>City</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Vehicle Type</th>
      <th>Vehicle Identification Number</th>
      <th>User ID</th>
      <th>Quoted</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @car_forms.each do |car_form| %>
      <tr>
        <td><%= car_form.id %></td>
        <td><%= car_form.city %></td>
        <td><%= car_form.address %></td>
        <td><%= car_form.phone_number %></td>
        <td><%= car_form.email %></td>
        <td><%= car_form.vehicle_type %></td>
        <td><%= car_form.vehicle_identification_number %></td>
        <td><%= car_form.user_id %></td>
        <td><%= car_form.quotations.any? ? 'Yes' : 'No' %></td>
        <td>
          <%= link_to 'Show', car_form_path(car_form), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>