config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  resources :car_forms do
    get 'user_car_forms', on: :collection
    post 'comments', to: 'car_forms#comment'
  end
  
  resources :admin do
    post 'attach_file', on: :member
    delete 'delete_attachment', on: :member
  end

  resources :quotations do
    put 'approval_and_rejection'
  end
  resources :quotation_items
end

app/controllers/car_form_controller.rb
class CarFormController < ApplicationController
  def new
    @car_form = CarForm.new
  end

  def create
    @car_form = CarForm.new(car_form_params)

    if @car_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def car_form_params
    params.require(:car_form).permit(
      :city,
      :address,
      :phone_number,
      :email,
      :vehicle_type,
      :vehicle_identification_number,
      :describe
    )
  end
end

app/controllers/car_forms_controller.rb
class CarFormsController < ApplicationController
  def show
    @car_form = CarForm.find(params[:id])
  end

  def new
    @car_form = CarForm.new
  end

  def create
    @car_form = CarForm.new(car_form_params)


    if @car_form.save
      @car_form.user = current_user
      redirect_to root_path
    else
      render :new
    end
  end

  def user_car_forms
    @car_forms = current_user.car_forms.includes(:quotations)
  end

  def comment
    @car_form = CarForm.find(params[:car_form_id])
    @comment = @car_form.comments.build(content: params[:quotation][:comments][:content])

    if @comment.save
      redirect_to @car_form
    else
      # Handle errors
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def car_form_params
    params.require(:car_form).permit(
      :city,
      :address,
      :phone_number,
      :email,
      :vehicle_type,
      :vehicle_identification_number,
      :describe,
      :user_id
    )
  end
end

app/views/car_form/new.html.erb
<!-- app/views/car_form/new.html.erb -->

<%= form_with(model: @car_form, url: car_form_index_path, method: :post) do |form| %>
  <!-- Display validation errors -->
  <% if @car_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_form.errors.count, "error") %> prohibited this car form from being saved:</h2>
      <ul>
        <% @car_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form fields for car_form attributes -->
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :vehicle_type %>
    <%= form.select :vehicle_type, CarForm.vehicle_types.keys %>
  </div>

  <div>
    <%= form.label :vehicle_identification_number %>
    <%= form.text_field :vehicle_identification_number %>
  </div>

  <div>
    <%= form.label :describe %>
    <%= form.text_area :describe %>
  </div>

  <!-- Submit button -->
  <div>
    <%= form.submit 'Submit Car Quotation' %>
  </div>
<% end %>