config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  resources :car_forms do
    get 'user_car_forms', on: :collection
    post 'comments', to: 'car_forms#comment'
  end
  
  resources :admin do
    post 'attach_file', on: :member
    delete 'delete_attachment', on: :member
  end

  resources :quotations do
    put 'approval_and_rejection'
  end
  resources :quotation_items
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @total_car_forms = current_user.car_forms.count
    @car_forms_with_quotations = current_user.car_forms.joins(:quotations).distinct.count
    @car_forms_without_quotations = current_user.car_forms.left_joins(:quotations).where(quotations: { id: nil }).count
  end
end

app/views/home/index.html.erb
<section style="display: flex; flex-direction: column; align-items: center; text-align: center;">
  <h1>Car Hub!</h1>

  <% if user_signed_in? %>
    <!-- Display the sign-out button when the user is signed in -->
    <%= link_to 'Sign Out', destroy_user_session_path, method: :get, class: 'sign-out-button' %>
  <% end %>

  <%= link_to 'Create Car Quotation', new_car_form_path, class: 'create-quotation-button' %>

  <%= link_to 'Admin Panel', admin_index_path, class: 'create-quotation-button' %>

  <!-- app/views/users/index.html.erb -->

<h1>Welcome <%= current_user.first_name %>!</h1>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Your Car Forms</h5>
    <p class="card-text">Total Car Forms: <%= @total_car_forms %></p>
    <p class="card-text">Car Forms with Quotations: <%= @car_forms_with_quotations %></p>
    <p class="card-text">Car Forms without Quotations: <%= @car_forms_without_quotations %></p>
  </div>

  <%= link_to 'Your Car Forms', user_car_forms_car_forms_path, class: 'btn btn-primary' %>
</div>

</section>